logging:
  file: O:\MIH\logs\MIHOnline.log
  level:
   ROOT: ERROR   
   org.springframework.data: DEBUG
   com.ehs.mihonline: DEBUG
   org.hibernate: ERROR 
#      type: debug 
#        web: DEBUG   
#      hibernate: DEBUG  
---
spring:
 profiles: local,default
 datasource:
  url: jdbc:sqlserver://10.200.7.220:1433;databaseName=MIH;integratedSecurity=true;
  username: 
  password:
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver    
 jpa:
  show-sql: true
  properties: 
    hibernate: 
      show_sql: true
    
#    ddl-auto: create-drop
 mail:
  properties:
   mail:
    smtp:
     connecttimeout: 5000
     timeout: 3000
     writetimeout: 5000
---
spring:
  profiles: prod
  datasource:
   url: jdbc:sqlserver://10.200.7.220:1433;databaseName=MIH;integratedSecurity=true;
   username: 
   password:
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver    
  jpa:
   show-sql: true
logging:
 file:
  O:\MIH\logs\MIHOnline.log
#   hibernate:
#    dialect: SQLServer2012Dialect
#     hbm2ddl:
#      method: update


